# Simple WES test : FastQC + BWA-MEM + sorted BAM.

import pandas as pd

configfile: "config/config.yaml"

samples_df = pd.read_csv("config/samples.csv")
SAMPLES = samples_df["sample"].tolist()

REF = config["reference"]
OUTDIR = config["outdir"]
QC_DIR = config["qc_dir"]


def fq(sample, read):
    """Return FASTQ path for a given sample and read (1 or 2)."""
    row = samples_df.set_index("sample").loc[sample]
    return row[f"fastq{read}"]


rule all:
    input:
        expand(f"{OUTDIR}/bam/{{sample}}.sorted.bam", sample=SAMPLES)


include: "rules/qc.smk"
include: "rules/mapping.smk"
